openapi: 3.0.1
info:
  title: Text Generator API
  description: 'API docs for Text Generator Feature.'
  termsOfService: http://dummy.io/terms/
  contact:
    email: saichandrasekar@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:3000
tags:
- name: text
  description:  About the text gen 
- name: monitoring
  description: Monitor for the app
paths:  
  /text:
    post:
      tags:
      - text
      summary: Add a new employee to the store
      operationId: addEmployee
      requestBody:
        description: employee object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextGenRequest'
        required: true
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextGenRequest'  
        405:
          description: Invalid input
          content: {}
      security:
      - mayur_auth:
        - write:employees
        - read:employees
      x-codegen-request-body-name: body    
  /monitor/isalive:
    get:
      tags:
      - monitoring
      responses:
        200:
          description: App is up and running
components:
  schemas:
    TextGenRequest:
      required:
      - textLength
      type: object
      properties:
        textLength:
          type: integer
          format: int64
        genCount:
          type: integer
          format: int64
        frequency:
          type: integer
          format: int64
        parallel:
          type: integer
          format: int64
  securitySchemes:
    mayur_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://mayur.swagger.io/oauth/dialog
          scopes:
            write:text: modify text in your account
            read:text: read your text            
    api_key:
      type: apiKey
      name: api_key
      in: header
